// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowRightOnRectangleIcon: typeof import('./components/ArrowRightOnRectangleIcon.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
    TodoCard: typeof import('./components/TodoCard.vue')['default']
  }
}
